import React from "react";
import { CardWrapper } from "@/components/auth/cardWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <CardWrapper
      label="Forgot your password?"
      backButtonHref={"/auth/login"}
      backButtonLabel={"Back to Login"}
    >
      <div className="flex items-center w-full justify-center">{children}</div>
    </CardWrapper>
  );
}
